---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019-09-05 17:32
---

-- tagList 指定界面列表
function F获取指定当前页面(tagList) --获取当前页面函数
    local res = '未知页面'
    for _, v in pairs(tagList) do
        --		print(v)
        local x, y = F多点找色(v[2])
        if x >=0 and y>=0 then
            globalX = x;
            globalY = y;
            res = v[1]  --界面名称
            break
        end
    end
    sysLog("F获取指定当前页面 ->"..res.."  坐标点: x->"..globalX.."  y-> "..globalY)
    return res
end

function F多点找色(v)
    return findColor(v[1],v[2],95, 0, 0, 0)
end


function F关闭所有页面()
    while true do
        mSleep(math.random(800,1000))
        local var = F获取指定当前页面(closeList)
        if var == "未知页面" then
            return
        else
            F单击()
            mSleep(math.random(800,1000))
        end
    end
end

function F单击()
    local hudId = createHUD()
    print("F单击 -> x :"..globalX..", y:"..globalY)
    local loaclX = math.random(globalX,globalX+10)
    local loaclY = math.random(globalY,globalY+10)
    showHUD(hudId,"",1,"0xffff0000","14.png",0,globalX,globalY,80,80)      --显示HUD内容

    touchDown(1, loaclX, loaclY)
    mSleep(math.random(100,300))
    touchMove(1, loaclX, loaclY)
    mSleep(math.random(100,300))
    touchUp(1, loaclX, loaclY)
    hideHUD(hudId)
end

--[[
dir == 滑动方向  -1 上滑动 1 下滑
way == 滑动方式  1 单位滑动, 2 极限滑动(滑动到最上 或者最下)
param
]]

function movePage(dir, way, renge)

    if dir == -1 then
        -- 上滑动 取右下坐标x2,y2
        globalX,globalY =math.random(renge.x1,renge.x2),renge.y2
    else
        -- 下滑动 取左上角坐标x1,y1
        globalX,globalY =math.random(renge.x1,renge.x2),renge.y1
    end
    local i = 3;
    while i>0 do
        local hudId = createHUD()
        local y = 0;
        mSleep(math.random(300,500))
        touchDown(1, globalX, globalY)
        showHUD(hudId,"",1,"0xffff0000","14.png",0,globalX,globalY,90,90)      --显示HUD内容

        mSleep(math.random(300,450))
        if way == 1 then
            local aa = dir*renge.rex
            y = globalY +  aa
            print("单位滑动:"..aa)
        else
            --极限滑动, 区间在200 - 300 内随机
            local aa = dir*math.random(200,300)
            y = globalY + aa
            print("极限移动:"..aa)
        end

        touchMove(1, globalX, y)
        mSleep(math.random(500,800))
        touchUp(1, globalX, y)

        if way == 1 then
            return
        else
            i = i-1
        end
        hideHUD(hudId)
    end


end

